---
 
.travis.yml:
  extras:
  - rvm: 2.4.0
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/debian-8
    services: docker
    sudo: required
    bundler_args: --without development
    dist: trusty
  - rvm: 2.4.0
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    services: docker
    sudo: required
    bundler_args: --without development
    dist: trusty
